# Lineage first assigned time analysis

In [1]:
import pandas as pd

In [2]:
timesum=pd.read_csv('designated_summary.csv')
relation=pd.read_csv('des_relation.csv')
relation

,Unnamed: 0,taxon,designated,pango,usher,n_count,des_expand,pango_expand,usher_expand,pango_relation,usher_relation
0,0,Afghanistan/IMB07960/2020,B.1.9,B.1.9,B.1.9,494,B.1.9,B.1.9,B.1.9,Agree,Agree
1,1,Afghanistan/IMB07970/2020,B.1.9,B.1.9,B.1.9,494,B.1.9,B.1.9,B.1.9,Agree,Agree
2,2,Albania/Cento-30536457/2020,B.1.236,B.1.236,B.1.236,494,B.1.236,B.1.236,B.1.236,Agree,Agree
3,3,Algeria/G37138-8854/2020,B.1.597,B.1.597,B.1.597,494,B.1.597,B.1.597,B.1.597,Agree,Agree
4,4,Algeria/G38882-8853/2020,B.1.597,B.1.597,B.1.597,494,B.1.597,B.1.597,B.1.597,Agree,Agree
...,...,...,...,...,...,...,...,...,...,...,...
246315,246315,Zimbabwe/ZW-9095/2020,B.1.1.459,B.1.1.459,B.1.1.459,1438,B.1.1.459,B.1.1.459,B.1.1.459,Agree,Agree
246316,246316,Zimbabwe/ZW-9096/2020,B.1.1.459,B.1.1.459,B.1.1.459,817,B.1.1.459,B.1.1.459,B.1.1.459,Agree,Agree
246317,246317,Zimbabwe/ZW-9100/2020,B.1.1.459,B.1.1.459,B.1.1.459,1053,B.1.1.459,B.1.1.459,B.1.1.459,Agree,Agree
246318,246318,Zimbabwe/ZW-9102/2020,B.1.1.459,B.1.1.459,B.1.1.459,806,B.1.1.459,B.1.1.459,B.1.1.459,Agree,Agree
246319,246319,Zimbabwe/ZW-9521/2020,B.1,B.1,B.1,634,B.1,B.1,B.1,Agree,Agree

In [3]:

earlytime=timesum[['lineage','earliest_date']]
earlytime

        lineage earliest_date
0       AY.25.1    2020-12-26
1         AY.45    2021-03-18
2         AY.54    2021-02-10
3        AY.122    2020-09-07
4          BA.1    2021-01-17
...         ...           ...
1595    B.1.617    2021-02-25
1596    B.1.500    2020-08-10
1597  B.1.1.271    2020-03-11
1598   B.1.1.30    2020-05-18
1599    B.1.316    2020-04-29

[1600 rows x 2 columns]

In [4]:
list454=['B.1.596',
 'B.1.1.419',
 'B.1.564',
 'B.1.260',
 'B.1.160.14',
 'B.1.119',
 'B.6.6',
 'C.36.3',
 'B.1.160.32',
 'B.1.617.2',
 'B.1.160.33',
 'AY.122',
 'B.1',
 'AY.4.2',
 'B.1.284',
 'B.1.177.44',
 'B.1.340',
 'B.1.411',
 'AY.96',
 'B.1.222',
 'B',
 'B.1.177.43',
 'B.55',
 'AY.129',
 'B.1.160.30',
 'B.1.1.39',
 'B.1.576',
 'B.1.236',
 'B.1.128',
 'B.1.509',
 'B.1.612',
 'B.1.1.398',
 'B.1.595',
 'AY.25',
 'AY.57',
 'B.28',
 'B.1.311',
 'AY.110',
 'B.1.520',
 'B.1.1.74',
 'B.1.518',
 'B.1.516',
 'B.1.313',
 'P.1.14',
 'B.1.333',
 'B.1.1.121',
 'B.1.465',
 'B.1.395',
 'B.1.160.20',
 'AY.103']

In [5]:
earlytime.loc[earlytime['lineage'].isin(list454)]

         lineage earliest_date
3         AY.122    2020-09-07
8         AY.4.2    2021-06-08
14        AY.103    2021-04-19
29     B.1.617.2    2021-01-07
36       B.1.595    2020-03-12
48           B.1    2020-01-24
78         AY.25    2021-04-18
83        P.1.14    2020-11-03
108            B    2019-12-24
124       AY.129    2021-03-09
143       AY.110    2021-04-16
144      B.1.222    2020-02-24
168        B.6.6    2020-03-13
201      B.1.284    2020-03-16
214       C.36.3    2021-02-20
322     B.1.1.74    2020-03-25
359      B.1.311    2020-03-31
380      B.1.128    2020-03-13
439         B.28    2020-03-09
446      B.1.465    2020-03-11
452    B.1.1.419    2020-03-18
455         B.55    2020-01-29
467      B.1.395    2020-03-07
501      B.1.509    2020-04-18
505      B.1.564    2020-03-24
507     B.1.1.39    2020-07-01
509      B.1.236    2020-06-24
557      B.1.576    2020-03-29
624      B.1.518    2020-03-21
631      B.1.119    2020-03-12
704      B.1.340    2020-06-24
715        AY.57    2021-04-21
724   B.1.160.14    2020-09-01
726   B.1.160.32    2020-10-02
727   B.1.160.20    2020-10-12
732      B.1.313    2020-04-01
734      B.1.516    2020-03-11
748      B.1.596    2020-04-11
752      B.1.411    2020-10-03
833   B.1.177.43    2020-08-17
835   B.1.177.44    2020-08-10
863      B.1.612    2020-03-11
866      B.1.520    2020-03-25
876    B.1.1.121    2020-03-31
887    B.1.1.398    2020-03-19
1223     B.1.260    2020-03-24
1233  B.1.160.30    2020-10-06
1395     B.1.333    2020-03-17
1450  B.1.160.33    2020-10-30

In [47]:
usherb=pd.read_csv('usher_b.csv')
#usherb
b_clean=usherb.loc[usherb['count']>=30]
b=b_clean.groupby('designated').count()

index_list = list(b.index.values)
bad_b=earlytime.loc[earlytime['lineage'].isin(index_list)]
len(bad_b.loc[bad_b['earliest_date'].str.contains('2020-12')])

1

In [85]:
pangorelation=relation[['designated',"pango_relation",'taxon']].groupby(['designated',"pango_relation"]).count()
p_unstack=pangorelation.unstack(level=1)

p2=p_unstack.apply(lambda x: x/x.sum(), axis=1).reset_index()
for col in p2.columns:
    print(col)
p2

('designated', '')
('taxon', '1st child')
('taxon', '1st parent')
('taxon', 'Agree')
('taxon', 'Direct siblings')
('taxon', 'Unrelated')
('taxon', 'Untested')
('taxon', 'ancestor')
('taxon', 'downstream child')

               designated     taxon                                       \
pango_relation            1st child 1st parent     Agree Direct siblings
0                       A   0.00409        NaN  0.993865             NaN
1                     A.1       NaN        NaN  1.000000             NaN
2                    A.11       NaN        NaN  1.000000             NaN
3                    A.12       NaN        NaN  1.000000             NaN
4                    A.15       NaN        NaN  1.000000             NaN
...                   ...       ...        ...       ...             ...
1571                   XA       NaN        NaN  1.000000             NaN
1572                   XB       NaN        NaN  1.000000             NaN
1573                   XC       NaN        NaN  1.000000             NaN
1574                  Y.1       NaN        NaN  1.000000             NaN
1575                  Z.1       NaN        NaN  0.993506             NaN


pango_relation Unrelated Untested  ancestor downstream child
0               0.002045      NaN       NaN              NaN
1                    NaN      NaN       NaN              NaN
2                    NaN      NaN       NaN              NaN
3                    NaN      NaN       NaN              NaN
4                    NaN      NaN       NaN              NaN
...                  ...      ...       ...              ...
1571                 NaN      NaN       NaN              NaN
1572                 NaN      NaN       NaN              NaN
1573                 NaN      NaN       NaN              NaN
1574                 NaN      NaN       NaN              NaN
1575                 NaN      NaN  0.006494              NaN

[1576 rows x 9 columns]

In [104]:
p3=p2[[('designated', ''),('taxon', 'Agree')]]
p4=p3.set_axis(['lineage','accuracy'],axis=1)
p4

     lineage  accuracy
0          A  0.993865
1        A.1  1.000000
2       A.11  1.000000
3       A.12  1.000000
4       A.15  1.000000
...      ...       ...
1571      XA  1.000000
1572      XB  1.000000
1573      XC  1.000000
1574     Y.1  1.000000
1575     Z.1  0.993506

[1576 rows x 2 columns]

In [105]:
earlytime

        lineage earliest_date
0       AY.25.1    2020-12-26
1         AY.45    2021-03-18
2         AY.54    2021-02-10
3        AY.122    2020-09-07
4          BA.1    2021-01-17
...         ...           ...
1595    B.1.617    2021-02-25
1596    B.1.500    2020-08-10
1597  B.1.1.271    2020-03-11
1598   B.1.1.30    2020-05-18
1599    B.1.316    2020-04-29

[1600 rows x 2 columns]

In [108]:
p_sumdf=pd.merge(p4,earlytime,how='left',on=['lineage'])

p_sumdf.to_csv('p_time_acc.csv')

In [120]:
u1=relation[['designated',"usher_relation",'taxon']].groupby(['designated',"usher_relation"]).count().unstack(level=1)
u2=u1.apply(lambda x: x/x.sum(), axis=1).reset_index()
u3=u2[[('designated', ''),('taxon', 'Agree')]].set_axis(['lineage','accuracy'],axis=1)
u_sumdf=pd.merge(u3,earlytime,how='left',on=['lineage'])
u_sumdf.to_csv('u_time_acc.csv')

### N content of des

In [9]:
des_n=pd.read_csv('des_n_dis.csv')

In [136]:
des_n_clean=des_n.drop(columns=['Unnamed: 0'])

n1=des_n_clean.groupby(by='designated').mean('n_count').reset_index()
n2=n1.rename(columns={'designated':'lineage'})

time_n=pd.merge(n2,earlytime,how='left',on=['lineage'])
time_n.to_csv('time_N.csv')

In [143]:
import numpy as np
des_n['p_agree']=np.where(des_n['designated']==des_n['pango'],'yes','no')
des_n['u_agree']=np.where(des_n['designated']==des_n['usher'],'yes','no')

,Unnamed: 0,taxon,designated,pango,usher,n_count,p_agree,u_agree
0,0,Afghanistan/IMB07960/2020,B.1.9,B.1.9,B.1.9,494,yes,yes
1,1,Afghanistan/IMB07970/2020,B.1.9,B.1.9,B.1.9,494,yes,yes
2,2,Albania/Cento-30536457/2020,B.1.236,B.1.236,B.1.236,494,yes,yes
3,3,Algeria/G37138-8854/2020,B.1.597,B.1.597,B.1.597,494,yes,yes
4,4,Algeria/G38882-8853/2020,B.1.597,B.1.597,B.1.597,494,yes,yes
...,...,...,...,...,...,...,...,...
246315,246315,Zimbabwe/ZW-9095/2020,B.1.1.459,B.1.1.459,B.1.1.459,1438,yes,yes
246316,246316,Zimbabwe/ZW-9096/2020,B.1.1.459,B.1.1.459,B.1.1.459,817,yes,yes
246317,246317,Zimbabwe/ZW-9100/2020,B.1.1.459,B.1.1.459,B.1.1.459,1053,yes,yes
246318,246318,Zimbabwe/ZW-9102/2020,B.1.1.459,B.1.1.459,B.1.1.459,806,yes,yes
246319,246319,Zimbabwe/ZW-9521/2020,B.1,B.1,B.1,634,yes,yes

In [156]:
exlist= relation['taxon'].loc[(relation['designated']!=relation['usher'])&
                            (relation['designated']!=relation['pango'])&
                            (relation['pango']==relation['usher'])].tolist()
des2=des_n[des_n.taxon.isin(exlist)==False].drop(columns=['Unnamed: 0'])
des2.loc[des2['u_agree'].str.contains('no')]

des2.to_csv('volion_test.csv')

In [152]:
p_nolist=des2.loc[des2['p_agree']=='no','n_count'].tolist()
p_yeslist=des2.loc[des2['p_agree']=='yes','n_count'].tolist()

u_nolist=des2.loc[des2['u_agree']=='no','n_count'].tolist()
u_yeslist=des2.loc[des2['u_agree']=='yes','n_count'].tolist()

In [153]:
from random import sample 
from scipy import stats

## PangoLEARN decision Tree N content T-test result!

In [154]:
num=100
for _ in range(num):
    p_yessample=sample(p_yeslist,299)
    print(stats.ttest_ind(p_nolist, p_yessample, equal_var = False))
    
#all significant

Ttest_indResult(statistic=4.093363998828434, pvalue=4.890868208510512e-05)
Ttest_indResult(statistic=4.187580260065832, pvalue=3.299342383744378e-05)
Ttest_indResult(statistic=3.356474031963208, pvalue=0.0008421787576172487)
Ttest_indResult(statistic=4.511065902682182, pvalue=7.918178581950783e-06)
Ttest_indResult(statistic=4.079756209703036, pvalue=5.185294581182514e-05)
Ttest_indResult(statistic=3.7718985923789083, pvalue=0.00017944809973071367)
Ttest_indResult(statistic=4.338738557742073, pvalue=1.717691140661403e-05)
Ttest_indResult(statistic=4.1424434436527395, pvalue=3.9970565268541595e-05)
Ttest_indResult(statistic=3.656012991304592, pvalue=0.0002803675263957967)
Ttest_indResult(statistic=4.600941099252939, pvalue=5.236812425952111e-06)
Ttest_indResult(statistic=3.6281650846579985, pvalue=0.00031233270237894663)
Ttest_indResult(statistic=3.8418755933544753, pvalue=0.00013623305932436772)
Ttest_indResult(statistic=2.1643688992671177, pvalue=0.03083999344945983)
Ttest_indResult(statistic=3.7614486347124276, pvalue=0.0001868166094209616)
Ttest_indResult(statistic=3.442320602524714, pvalue=0.0006195091200205771)
Ttest_indResult(statistic=5.276880203296448, pvalue=1.958227557330535e-07)
Ttest_indResult(statistic=3.2096610204673643, pvalue=0.0014061500694335725)
Ttest_indResult(statistic=4.401621798879262, pvalue=1.2893777804554273e-05)
Ttest_indResult(statistic=4.409919970035598, pvalue=1.2418880733859805e-05)
Ttest_indResult(statistic=4.497644990849438, pvalue=8.416845888771597e-06)
Ttest_indResult(statistic=3.6016444900873035, pvalue=0.0003446441284549332)
Ttest_indResult(statistic=5.246490761414759, pvalue=2.3039598222722372e-07)
Ttest_indResult(statistic=3.9643361217007045, pvalue=8.337079784274716e-05)
Ttest_indResult(statistic=2.647741577559582, pvalue=0.008322594434085707)
Ttest_indResult(statistic=4.56018343802279, pvalue=6.341526499690777e-06)
Ttest_indResult(statistic=4.3687931704353264, pvalue=1.5004580714970567e-05)
Ttest_indResult(statistic=4.789180487269037, pvalue=2.194991038984412e-06)
Ttest_indResult(statistic=4.029097511738996, pvalue=6.385105806640437e-05)
Ttest_indResult(statistic=4.214078581974084, pvalue=2.9554678900351977e-05)
Ttest_indResult(statistic=3.796612358006392, pvalue=0.0001628882247192434)
Ttest_indResult(statistic=3.67782134434059, pvalue=0.00025799478149488155)
Ttest_indResult(statistic=3.6543892458178555, pvalue=0.00028216262650677173)
Ttest_indResult(statistic=3.80743529984687, pvalue=0.0001559899284090933)
Ttest_indResult(statistic=2.9994164205134837, pvalue=0.00282139482597559)
Ttest_indResult(statistic=5.514401234318812, pvalue=5.624414706560498e-08)
Ttest_indResult(statistic=4.304036703270777, pvalue=1.9943562846109925e-05)
Ttest_indResult(statistic=3.0150504377132394, pvalue=0.002680661157249062)
Ttest_indResult(statistic=3.3320999756538003, pvalue=0.0009197292392716515)
Ttest_indResult(statistic=3.9253075054296214, pvalue=9.780421821691988e-05)
Ttest_indResult(statistic=3.7589822126813344, pvalue=0.00018903484168222997)
Ttest_indResult(statistic=3.6611243011794823, pvalue=0.00027462327213328573)
Ttest_indResult(statistic=3.5535566784041337, pvalue=0.0004117304903949832)
Ttest_indResult(statistic=3.691089383936593, pvalue=0.0002457583962309524)
Ttest_indResult(statistic=3.796818885778008, pvalue=0.0001628997417833415)
Ttest_indResult(statistic=3.2592313804969613, pvalue=0.0011849405398167959)
Ttest_indResult(statistic=3.4050965735955714, pvalue=0.00070807618418956)
Ttest_indResult(statistic=4.105697193657167, pvalue=4.648857907195333e-05)
Ttest_indResult(statistic=4.573769081244627, pvalue=5.910821389300326e-06)
Ttest_indResult(statistic=3.466742152625491, pvalue=0.0005662546944764608)
Ttest_indResult(statistic=4.99071433898369, pvalue=8.21282782330827e-07)
Ttest_indResult(statistic=4.705560789051501, pvalue=3.2395942550357574e-06)
Ttest_indResult(statistic=3.9421860739381103, pvalue=9.094640665250363e-05)
Ttest_indResult(statistic=4.270400192163803, pvalue=2.3129139069688838e-05)
Ttest_indResult(statistic=4.077745658675578, pvalue=5.233807352368974e-05)
Ttest_indResult(statistic=4.374236073706079, pvalue=1.4637758282752582e-05)
Ttest_indResult(statistic=4.317833219365099, pvalue=1.8803006386114733e-05)
Ttest_indResult(statistic=2.446983810549014, pvalue=0.014699277907528965)
Ttest_indResult(statistic=3.5549376025282093, pvalue=0.0004100414992769353)
Ttest_indResult(statistic=5.045555533206725, pvalue=6.192193744748216e-07)
Ttest_indResult(statistic=3.8170019302375717, pvalue=0.00015042653832544488)
Ttest_indResult(statistic=2.4193065442616057, pvalue=0.015858915987127995)
Ttest_indResult(statistic=3.8637187222907468, pvalue=0.000124855196612286)
Ttest_indResult(statistic=5.319270726654317, pvalue=1.5537084979736019e-07)
Ttest_indResult(statistic=4.038061964534975, pvalue=6.148031287145093e-05)
Ttest_indResult(statistic=3.930741996780311, pvalue=9.516205979012406e-05)
Ttest_indResult(statistic=4.177736674480467, pvalue=3.442459476156455e-05)
Ttest_indResult(statistic=2.9140167286695964, pvalue=0.003705574085603172)
Ttest_indResult(statistic=5.144915886033631, pvalue=3.8425336019635656e-07)
Ttest_indResult(statistic=3.3053903427785136, pvalue=0.001009344407918497)
Ttest_indResult(statistic=2.2468093163640583, pvalue=0.02502613885966245)
Ttest_indResult(statistic=3.639371836201578, pvalue=0.000298846291676489)
Ttest_indResult(statistic=4.360907378180616, pvalue=1.550085254325986e-05)
Ttest_indResult(statistic=4.8656486808433055, pvalue=1.5093724246992787e-06)
Ttest_indResult(statistic=3.973178761232134, pvalue=8.038795152026822e-05)
Ttest_indResult(statistic=3.43737314117383, pvalue=0.0006306703627281526)
Ttest_indResult(statistic=2.4110848135132734, pvalue=0.016213775792749827)
Ttest_indResult(statistic=3.0863035153919713, pvalue=0.002124603688791346)
Ttest_indResult(statistic=3.1997966141535406, pvalue=0.0014516651821117603)
Ttest_indResult(statistic=4.352703508396412, pvalue=1.6181213869664406e-05)
Ttest_indResult(statistic=4.640227679216741, pvalue=4.41276355367752e-06)
Ttest_indResult(statistic=3.369266087839699, pvalue=0.000806378771196538)
Ttest_indResult(statistic=4.500718553572272, pvalue=8.306371490606484e-06)
Ttest_indResult(statistic=4.863155174189473, pvalue=1.5419703071410157e-06)
Ttest_indResult(statistic=4.24760178362404, pvalue=2.545985473512827e-05)
Ttest_indResult(statistic=3.519870358854006, pvalue=0.0004674522306426726)
Ttest_indResult(statistic=3.6704256820141192, pvalue=0.0002655242769411621)
Ttest_indResult(statistic=3.629775764580023, pvalue=0.00031007477939752387)
Ttest_indResult(statistic=4.006976572019587, pvalue=7.027797988007936e-05)
Ttest_indResult(statistic=4.57668914865185, pvalue=5.8592881748314285e-06)
Ttest_indResult(statistic=3.876496348239494, pvalue=0.00011871683822199609)
Ttest_indResult(statistic=3.6062813513634433, pvalue=0.0003385486760122551)
Ttest_indResult(statistic=4.627673267668021, pvalue=4.679728778934973e-06)
Ttest_indResult(statistic=3.1303815417520298, pvalue=0.0018364144416803396)
Ttest_indResult(statistic=4.53322834646815, pvalue=7.229664239396272e-06)
Ttest_indResult(statistic=3.413134680010985, pvalue=0.000687633015379524)
Ttest_indResult(statistic=4.025675514293511, pvalue=6.486503196465764e-05)
Ttest_indResult(statistic=3.790102781892668, pvalue=0.0001669264803057734)
Ttest_indResult(statistic=3.5873484301178715, pvalue=0.0003629254181018645)
Ttest_indResult(statistic=4.115332268196899, pvalue=4.463265857279226e-05)
Ttest_indResult(statistic=4.195495054691339, pvalue=3.1760291400652015e-05)

## UShER N content T-test result!

In [155]:
num=100
for _ in range(num):
    u_yessample=sample(u_yeslist,10208)
    print(stats.ttest_ind(u_nolist, u_yessample, equal_var = False))
    
#Ttest_indResult(statistic=1.69567213294207, pvalue=0.08996327668914332)

Ttest_indResult(statistic=3.0598619953247796, pvalue=0.0022172802365154646)
Ttest_indResult(statistic=3.6568227756764036, pvalue=0.00025600675793064324)
Ttest_indResult(statistic=3.737723787476365, pvalue=0.00018620444151505751)
Ttest_indResult(statistic=3.5380285205941653, pvalue=0.00040402917091722875)
Ttest_indResult(statistic=2.6819608911441204, pvalue=0.007325131322390476)
Ttest_indResult(statistic=3.24219986806881, pvalue=0.001188027774768198)
Ttest_indResult(statistic=3.035750252329456, pvalue=0.00240241767163631)
Ttest_indResult(statistic=3.6420869449828626, pvalue=0.00027111218364000316)
Ttest_indResult(statistic=4.029780841491906, pvalue=5.6032675243499144e-05)
Ttest_indResult(statistic=2.621418259573781, pvalue=0.008763002598673733)
Ttest_indResult(statistic=3.90413270130239, pvalue=9.487049910564431e-05)
Ttest_indResult(statistic=4.004180164076766, pvalue=6.245529368624969e-05)
Ttest_indResult(statistic=4.272103285955962, pvalue=1.9452108601758957e-05)
Ttest_indResult(statistic=3.524055841327467, pvalue=0.0004259319269736726)
Ttest_indResult(statistic=2.944964114680675, pvalue=0.0032335878870161988)
Ttest_indResult(statistic=3.9428613053923964, pvalue=8.07866603316145e-05)
Ttest_indResult(statistic=3.630734930108297, pvalue=0.0002833118248709563)
Ttest_indResult(statistic=5.2262106416589145, pvalue=1.7474385249020966e-07)
Ttest_indResult(statistic=2.9636176099266813, pvalue=0.003043993181172198)
Ttest_indResult(statistic=1.69567213294207, pvalue=0.08996327668914332)
Ttest_indResult(statistic=3.2637348086635356, pvalue=0.001101359197974276)
Ttest_indResult(statistic=3.2112874570072236, pvalue=0.0013234806083873064)
Ttest_indResult(statistic=4.543535316181124, pvalue=5.563887289247792e-06)
Ttest_indResult(statistic=3.7683847164518647, pvalue=0.00016477248860908458)
Ttest_indResult(statistic=4.323915708735792, pvalue=1.5401690720065054e-05)
Ttest_indResult(statistic=3.827595171425877, pvalue=0.00012979160668155043)
Ttest_indResult(statistic=3.024711249684578, pvalue=0.0024918242887982363)
Ttest_indResult(statistic=3.1253330160797614, pvalue=0.0017785427831933)
Ttest_indResult(statistic=3.616023094915651, pvalue=0.0002998897768258701)
Ttest_indResult(statistic=3.2618102743034756, pvalue=0.0011088608331797259)
Ttest_indResult(statistic=3.1969167572764077, pvalue=0.0013911814042268443)
Ttest_indResult(statistic=3.5687695960444468, pvalue=0.00035949214192316386)
Ttest_indResult(statistic=3.274617659921434, pvalue=0.0010598228923679512)
Ttest_indResult(statistic=3.938431193168326, pvalue=8.229127227422529e-05)
Ttest_indResult(statistic=2.4184706556866478, pvalue=0.015594630411861666)
Ttest_indResult(statistic=2.5991167885827675, pvalue=0.009353144383364804)
Ttest_indResult(statistic=3.280813751918926, pvalue=0.0010368288175641221)
Ttest_indResult(statistic=1.8212518123043542, pvalue=0.06858328139329789)
Ttest_indResult(statistic=2.97386732863503, pvalue=0.002944188345322505)
Ttest_indResult(statistic=3.3398219768115998, pvalue=0.0008398350145882644)
Ttest_indResult(statistic=3.1000276294664784, pvalue=0.0019376740650027798)
Ttest_indResult(statistic=3.0011854894220193, pvalue=0.0026925752363957415)
Ttest_indResult(statistic=2.2741465447391382, pvalue=0.022967558748386525)
Ttest_indResult(statistic=2.1733246472939776, pvalue=0.029767385007987996)
Ttest_indResult(statistic=3.0475932312093406, pvalue=0.0023097869955443404)
Ttest_indResult(statistic=4.632434354812318, pvalue=3.6364798112590684e-06)
Ttest_indResult(statistic=3.8901912234131912, pvalue=0.00010048539755713657)
Ttest_indResult(statistic=4.147791788684446, pvalue=3.370674333084529e-05)
Ttest_indResult(statistic=3.3168320188427267, pvalue=0.0009120428107859987)
Ttest_indResult(statistic=3.662413425596957, pvalue=0.00025048636166526356)
Ttest_indResult(statistic=2.6835082607347296, pvalue=0.007291326605944514)
Ttest_indResult(statistic=2.784992667985775, pvalue=0.005357849969077949)
Ttest_indResult(statistic=1.942618759472478, pvalue=0.05207602514587067)
Ttest_indResult(statistic=3.72463062147232, pvalue=0.00019613166967224818)
Ttest_indResult(statistic=3.6769067299400224, pvalue=0.00023668825522053737)
Ttest_indResult(statistic=3.3411927066233855, pvalue=0.0008357017651895219)
Ttest_indResult(statistic=3.401315512318071, pvalue=0.0006719212158126384)
Ttest_indResult(statistic=3.5635674263830097, pvalue=0.0003666886061786324)
Ttest_indResult(statistic=3.9282601598492675, pvalue=8.584627518786027e-05)
Ttest_indResult(statistic=2.8963268962537314, pvalue=0.003779620648466358)
Ttest_indResult(statistic=2.2530962387379834, pvalue=0.024263701092508486)
Ttest_indResult(statistic=2.771910567390258, pvalue=0.005577911883438258)
Ttest_indResult(statistic=2.248074554444163, pvalue=0.024582105689363525)
Ttest_indResult(statistic=3.594399947109623, pvalue=0.00032591210500873763)
Ttest_indResult(statistic=3.7485770784656496, pvalue=0.00017833570854293573)
Ttest_indResult(statistic=3.847608438467092, pvalue=0.00011964193362311576)
Ttest_indResult(statistic=3.815966944221831, pvalue=0.00013605364062128624)
Ttest_indResult(statistic=2.6403003335216546, pvalue=0.008289599640571582)
Ttest_indResult(statistic=3.8751893641263826, pvalue=0.00010687776795585178)
Ttest_indResult(statistic=2.9958161382524127, pvalue=0.002740419660174012)
Ttest_indResult(statistic=2.783749565929149, pvalue=0.005378428652550588)
Ttest_indResult(statistic=2.9848409890499297, pvalue=0.0028406382840375417)
Ttest_indResult(statistic=3.830485469358291, pvalue=0.00012827708706746293)
Ttest_indResult(statistic=3.804208903833659, pvalue=0.00014267629949979018)
Ttest_indResult(statistic=3.1515583071073947, pvalue=0.0016263795630904023)
Ttest_indResult(statistic=2.713049011162567, pvalue=0.006672348593191181)
Ttest_indResult(statistic=3.3556800112336407, pvalue=0.0007931555899901529)
Ttest_indResult(statistic=3.815696392038699, pvalue=0.0001362034656431533)
Ttest_indResult(statistic=4.161236160253587, pvalue=3.1783860244155536e-05)
Ttest_indResult(statistic=2.8623576329830085, pvalue=0.004209317339679252)
Ttest_indResult(statistic=3.3225972691571353, pvalue=0.0008934126026676321)
Ttest_indResult(statistic=3.402635016969305, pvalue=0.0006686828382746531)
Ttest_indResult(statistic=3.4003392657513625, pvalue=0.0006743199835035968)
Ttest_indResult(statistic=3.5074747268268966, pvalue=0.000453359351833862)
Ttest_indResult(statistic=3.6282302508846804, pvalue=0.00028607201796883937)
Ttest_indResult(statistic=3.5607316267007585, pvalue=0.000370671172386818)
Ttest_indResult(statistic=2.9571243037459616, pvalue=0.003108810100714695)
Ttest_indResult(statistic=4.310551373363584, pvalue=1.636168699213957e-05)
Ttest_indResult(statistic=3.041152914177843, pvalue=0.002359752275507217)
Ttest_indResult(statistic=2.276676637991122, pvalue=0.02281590561903054)
Ttest_indResult(statistic=2.5200578063384573, pvalue=0.011741162679898979)
Ttest_indResult(statistic=2.694901257049895, pvalue=0.007046743851743228)
Ttest_indResult(statistic=3.988362650219959, pvalue=6.676477520161958e-05)
Ttest_indResult(statistic=2.859999310793065, pvalue=0.004240743977076055)
Ttest_indResult(statistic=3.1941642274124824, pvalue=0.0014045088162685814)
Ttest_indResult(statistic=3.065789438066933, pvalue=0.0021738164584770396)
Ttest_indResult(statistic=3.4873939707063486, pvalue=0.0004887860646280802)
Ttest_indResult(statistic=3.09227094604243, pvalue=0.001989012081341896)
Ttest_indResult(statistic=3.7105321333578236, pvalue=0.00020737859448806729)
Ttest_indResult(statistic=2.558514565836695, pvalue=0.010519237924273898)

## Random Forest

note: the 454 sequences with agreement between results are excluded

In [5]:
timesum=pd.read_csv('designated_summary.csv')
r=pd.read_csv('rf_relation.csv')
r

,Unnamed: 0,Unnamed: 0.1,taxon,designated,pango,usher,rf_lineage,conflict,ambiguity_score,des_expand,rf_expand,rf_relation
0,0,0,Afghanistan/IMB07960/2020,B.1.9,B.1.9,B.1.9,B.1.9,0.08,1.00,B.1.9,B.1.9,Agree
1,1,1,Afghanistan/IMB07970/2020,B.1.9,B.1.9,B.1.9,B.1.9,0.00,1.00,B.1.9,B.1.9,Agree
2,2,2,Albania/Cento-30536457/2020,B.1.236,B.1.236,B.1.236,B.1.236,0.00,1.00,B.1.236,B.1.236,Agree
3,3,3,Algeria/G37138-8854/2020,B.1.597,B.1.597,B.1.597,B.1.597,0.20,1.00,B.1.597,B.1.597,Agree
4,4,4,Algeria/G38882-8853/2020,B.1.597,B.1.597,B.1.597,B.1.597,0.16,1.00,B.1.597,B.1.597,Agree
...,...,...,...,...,...,...,...,...,...,...,...,...
245861,246315,246315,Zimbabwe/ZW-9095/2020,B.1.1.459,B.1.1.459,B.1.1.459,B.1.1.459,0.00,0.95,B.1.1.459,B.1.1.459,Agree
245862,246316,246316,Zimbabwe/ZW-9096/2020,B.1.1.459,B.1.1.459,B.1.1.459,B.1.1.459,0.00,0.99,B.1.1.459,B.1.1.459,Agree
245863,246317,246317,Zimbabwe/ZW-9100/2020,B.1.1.459,B.1.1.459,B.1.1.459,B.1.1.459,0.00,0.97,B.1.1.459,B.1.1.459,Agree
245864,246318,246318,Zimbabwe/ZW-9102/2020,B.1.1.459,B.1.1.459,B.1.1.459,B.1.1.459,0.00,0.99,B.1.1.459,B.1.1.459,Agree
245865,246319,246319,Zimbabwe/ZW-9521/2020,B.1,B.1,B.1,B.1,0.00,0.99,B.1,B.1,Agree

In [8]:
earlytime=timesum[['lineage','earliest_date']]

r1=r[['designated',"rf_relation",'taxon']].groupby(['designated',"rf_relation"]).count().unstack(level=1)
r2=r1.apply(lambda x: x/x.sum(), axis=1).reset_index()
r3=r2[[('designated', ''),('taxon', 'Agree')]].set_axis(['lineage','accuracy'],axis=1)
r_sumdf=pd.merge(r3,earlytime,how='left',on=['lineage'])
r_sumdf
r_sumdf.to_csv('rf_time_acc.csv')

In [16]:
des_n

                              taxon designated      pango      usher  n_count
0         Afghanistan/IMB07960/2020      B.1.9      B.1.9      B.1.9      494
1         Afghanistan/IMB07970/2020      B.1.9      B.1.9      B.1.9      494
2       Albania/Cento-30536457/2020    B.1.236    B.1.236    B.1.236      494
3          Algeria/G37138-8854/2020    B.1.597    B.1.597    B.1.597      494
4          Algeria/G38882-8853/2020    B.1.597    B.1.597    B.1.597      494
...                             ...        ...        ...        ...      ...
246315        Zimbabwe/ZW-9095/2020  B.1.1.459  B.1.1.459  B.1.1.459     1438
246316        Zimbabwe/ZW-9096/2020  B.1.1.459  B.1.1.459  B.1.1.459      817
246317        Zimbabwe/ZW-9100/2020  B.1.1.459  B.1.1.459  B.1.1.459     1053
246318        Zimbabwe/ZW-9102/2020  B.1.1.459  B.1.1.459  B.1.1.459      806
246319        Zimbabwe/ZW-9521/2020        B.1        B.1        B.1      634

[246320 rows x 5 columns]

In [31]:
des_n=pd.read_csv('des_n_dis.csv').drop(columns=['Unnamed: 0'])

r_clean=r.drop(columns=['Unnamed: 0','Unnamed: 0.1','pango','usher','designated'])
des_clean=des_n[['taxon','designated','n_count']]
r_bigdf=pd.merge(des_clean,r_clean,how='left',on=['taxon'])

r_bigdf.to_csv('rf_anlysis.csv')
r_bigdf

,taxon,designated,n_count,rf_lineage,conflict,ambiguity_score,des_expand,rf_expand,rf_relation
0,Afghanistan/IMB07960/2020,B.1.9,494,B.1.9,0.08,1.00,B.1.9,B.1.9,Agree
1,Afghanistan/IMB07970/2020,B.1.9,494,B.1.9,0.00,1.00,B.1.9,B.1.9,Agree
2,Albania/Cento-30536457/2020,B.1.236,494,B.1.236,0.00,1.00,B.1.236,B.1.236,Agree
3,Algeria/G37138-8854/2020,B.1.597,494,B.1.597,0.20,1.00,B.1.597,B.1.597,Agree
4,Algeria/G38882-8853/2020,B.1.597,494,B.1.597,0.16,1.00,B.1.597,B.1.597,Agree
...,...,...,...,...,...,...,...,...,...
246315,Zimbabwe/ZW-9095/2020,B.1.1.459,1438,B.1.1.459,0.00,0.95,B.1.1.459,B.1.1.459,Agree
246316,Zimbabwe/ZW-9096/2020,B.1.1.459,817,B.1.1.459,0.00,0.99,B.1.1.459,B.1.1.459,Agree
246317,Zimbabwe/ZW-9100/2020,B.1.1.459,1053,B.1.1.459,0.00,0.97,B.1.1.459,B.1.1.459,Agree
246318,Zimbabwe/ZW-9102/2020,B.1.1.459,806,B.1.1.459,0.00,0.99,B.1.1.459,B.1.1.459,Agree
246319,Zimbabwe/ZW-9521/2020,B.1,634,B.1,0.00,0.99,B.1,B.1,Agree

In [1]:
from random import sample 
from scipy import stats
import numpy as np

In [36]:

r_bigdf['rf_agree']=np.where(r_bigdf['designated']==r_bigdf['rf_lineage'],'yes','no')


r_bigdf.to_csv('rf_anlysis.csv')

In [10]:
rf_n=pd.read_csv('rf_anlysis.csv')




nolist=rf_n.loc[rf_n['rf_agree']=='no','n_count'].tolist()
yeslist=rf_n.loc[rf_n['rf_agree']=='yes','n_count'].tolist()

yessample=sample(yeslist,782)

#stats.ttest_ind(nolist, yessample, equal_var = False)

num=100
for _ in range(num):
    yessample=sample(yeslist,490)
    print(stats.ttest_ind(nolist, yessample, equal_var = False))

Ttest_indResult(statistic=4.278799246943626, pvalue=2.0288427204349776e-05)
Ttest_indResult(statistic=5.942036669272557, pvalue=3.636929242024627e-09)
Ttest_indResult(statistic=6.069823156948038, pvalue=1.6981228899742457e-09)
Ttest_indResult(statistic=4.699835902117788, pvalue=2.903201040622748e-06)
Ttest_indResult(statistic=5.018745801386928, pvalue=5.976592315454903e-07)
Ttest_indResult(statistic=4.534047899580787, pvalue=6.360531641759566e-06)
Ttest_indResult(statistic=5.048208647216014, pvalue=5.136339792381488e-07)
Ttest_indResult(statistic=5.009822634625196, pvalue=6.257962421207085e-07)
Ttest_indResult(statistic=5.791408831016219, pvalue=8.834208407221358e-09)
Ttest_indResult(statistic=4.164901550669608, pvalue=3.3445070098618834e-05)
Ttest_indResult(statistic=5.266361349627805, pvalue=1.644114817687607e-07)
Ttest_indResult(statistic=4.458130397262232, pvalue=9.033970446128511e-06)
Ttest_indResult(statistic=5.687647501710794, pvalue=1.602068284869312e-08)
Ttest_indResult(statistic=5.250827638625375, pvalue=1.7803966994563448e-07)
Ttest_indResult(statistic=5.708087399512951, pvalue=1.4309369556539457e-08)
Ttest_indResult(statistic=4.648357443670157, pvalue=3.7165640506573932e-06)
Ttest_indResult(statistic=3.760115386336627, pvalue=0.00017794741550904814)
Ttest_indResult(statistic=2.9536605047132314, pvalue=0.003203957000161587)
Ttest_indResult(statistic=5.523480843247061, pvalue=4.052203678287362e-08)
Ttest_indResult(statistic=4.149597733068702, pvalue=3.56033099371632e-05)
Ttest_indResult(statistic=5.178222231122192, pvalue=2.6137289561815473e-07)
Ttest_indResult(statistic=4.054380842670217, pvalue=5.3546912207099e-05)
Ttest_indResult(statistic=5.254495167332077, pvalue=1.7487449598809697e-07)
Ttest_indResult(statistic=5.854502480270136, pvalue=6.102350150648377e-09)
Ttest_indResult(statistic=4.628262282298759, pvalue=4.085440555744337e-06)
Ttest_indResult(statistic=3.3716356251934942, pvalue=0.0007715479079858211)
Ttest_indResult(statistic=5.810561549286674, pvalue=7.908293422542827e-09)
Ttest_indResult(statistic=6.000492252521027, pvalue=2.578019664910081e-09)
Ttest_indResult(statistic=6.159385337056841, pvalue=9.833126219315096e-10)
Ttest_indResult(statistic=4.2664559003186735, pvalue=2.142300884235157e-05)
Ttest_indResult(statistic=5.780565505998828, pvalue=9.406265242267498e-09)
Ttest_indResult(statistic=3.96879641757988, pvalue=7.662979509780076e-05)
Ttest_indResult(statistic=5.345070387510573, pvalue=1.0763761219781055e-07)
Ttest_indResult(statistic=5.5914932525921826, pvalue=2.763901095673423e-08)
Ttest_indResult(statistic=4.750366999010954, pvalue=2.27405359853351e-06)
Ttest_indResult(statistic=5.196685767180339, pvalue=2.374756459550379e-07)
Ttest_indResult(statistic=4.854538939123346, pvalue=1.3618126390706517e-06)
Ttest_indResult(statistic=5.095671306033818, pvalue=4.0194047647608063e-07)
Ttest_indResult(statistic=6.5903661831389755, pvalue=6.439032128063862e-11)
Ttest_indResult(statistic=5.687907991959099, pvalue=1.6088354870125718e-08)
Ttest_indResult(statistic=5.529765338218038, pvalue=3.904855004465061e-08)
Ttest_indResult(statistic=4.476878915512305, pvalue=8.290562067203673e-06)
Ttest_indResult(statistic=3.4253068864239187, pvalue=0.0006353392682930726)
Ttest_indResult(statistic=4.937302845446609, pvalue=9.036826437053744e-07)
Ttest_indResult(statistic=5.281394111635164, pvalue=1.518916487551931e-07)
Ttest_indResult(statistic=6.600806795354816, pvalue=6.001286024128659e-11)
Ttest_indResult(statistic=4.191258879144606, pvalue=2.9787278536215707e-05)
Ttest_indResult(statistic=5.444136062676291, pvalue=6.288858360226622e-08)
Ttest_indResult(statistic=5.163861031590189, pvalue=2.824382479680165e-07)
Ttest_indResult(statistic=4.028839891412707, pvalue=5.961747958992663e-05)
Ttest_indResult(statistic=4.892784883739893, pvalue=1.1264400383969494e-06)
Ttest_indResult(statistic=6.001908768670566, pvalue=2.5495070749489974e-09)
Ttest_indResult(statistic=5.433912645790756, pvalue=6.6297966049163e-08)
Ttest_indResult(statistic=4.441040551496667, pvalue=9.779174115843213e-06)
Ttest_indResult(statistic=4.880092185591029, pvalue=1.2008390344781289e-06)
Ttest_indResult(statistic=4.361361592216742, pvalue=1.4030394886286615e-05)
Ttest_indResult(statistic=5.5945325647500646, pvalue=2.7204755320920007e-08)
Ttest_indResult(statistic=4.244769048478953, pvalue=2.357873584591198e-05)
Ttest_indResult(statistic=4.41862075805716, pvalue=1.0830149407883212e-05)
Ttest_indResult(statistic=4.267784983557467, pvalue=2.1300266859736453e-05)
Ttest_indResult(statistic=4.791975501827094, pvalue=1.8499671462090237e-06)
Ttest_indResult(statistic=5.700798293724238, pvalue=1.4876482560377437e-08)
Ttest_indResult(statistic=5.291389205095113, pvalue=1.4402611006746593e-07)
Ttest_indResult(statistic=6.0882780598719455, pvalue=1.5148237911536372e-09)
Ttest_indResult(statistic=6.223604077668573, pvalue=6.630481133677123e-10)
Ttest_indResult(statistic=5.908863192391192, pvalue=4.449277698409046e-09)
Ttest_indResult(statistic=4.641013171185889, pvalue=3.8397522972261766e-06)
Ttest_indResult(statistic=4.582482716664271, pvalue=5.069050466652865e-06)
Ttest_indResult(statistic=6.244158972498622, pvalue=5.823599456253214e-10)
Ttest_indResult(statistic=5.710661533210952, pvalue=1.4061024363479859e-08)
Ttest_indResult(statistic=4.401873452357112, pvalue=1.1678181475967589e-05)
Ttest_indResult(statistic=4.918311100261638, pvalue=9.953079750552778e-07)
Ttest_indResult(statistic=5.3069454153629625, pvalue=1.3226006214383764e-07)
Ttest_indResult(statistic=4.89291951377257, pvalue=1.1261809483916234e-06)
Ttest_indResult(statistic=4.808763340688783, pvalue=1.7062620355736021e-06)
Ttest_indResult(statistic=4.799809568387869, pvalue=1.785623763614004e-06)
Ttest_indResult(statistic=5.817639116710326, pvalue=7.581622229242433e-09)
Ttest_indResult(statistic=4.912475026531871, pvalue=1.0234865457952998e-06)
Ttest_indResult(statistic=3.76183299686351, pvalue=0.00017705025013723793)
Ttest_indResult(statistic=4.568917773649539, pvalue=5.417721486584376e-06)
Ttest_indResult(statistic=5.904613940498542, pvalue=4.5496804920027145e-09)
Ttest_indResult(statistic=4.83996919388525, pvalue=1.4635922942409102e-06)
Ttest_indResult(statistic=5.237369962744627, pvalue=1.9125089966527527e-07)
Ttest_indResult(statistic=5.0047015230410485, pvalue=6.395374559860056e-07)
Ttest_indResult(statistic=4.578823577230702, pvalue=5.15302019550746e-06)
Ttest_indResult(statistic=3.615067203643694, pvalue=0.0003131508350920179)
Ttest_indResult(statistic=3.81108926369816, pvalue=0.00014548810843846615)
Ttest_indResult(statistic=2.552630396747513, pvalue=0.010817623596671265)
Ttest_indResult(statistic=3.899094149044504, pvalue=0.00010199616572946752)
Ttest_indResult(statistic=5.759766772653269, pvalue=1.060425399964075e-08)
Ttest_indResult(statistic=5.63470405749121, pvalue=2.1674203345019665e-08)
Ttest_indResult(statistic=3.636456243172452, pvalue=0.00028815155532027154)
Ttest_indResult(statistic=4.342335924977486, pvalue=1.5291245457594805e-05)
Ttest_indResult(statistic=4.618839491923472, pvalue=4.26465532583189e-06)
Ttest_indResult(statistic=4.256060689536002, pvalue=2.2413387115982066e-05)
Ttest_indResult(statistic=5.855041636015621, pvalue=6.104352937082794e-09)
Ttest_indResult(statistic=4.070893361097551, pvalue=4.995898340772162e-05)
Ttest_indResult(statistic=5.478943658068552, pvalue=5.16782936874801e-08)
Ttest_indResult(statistic=4.834420227128758, pvalue=1.507282250300424e-06)
Ttest_indResult(statistic=6.0209795594803195, pvalue=2.275789993956732e-09)

## N content results:

Decision tree range: 0.031 ~ 1.5537084979736019e-07

Random Forest range:0.010817623596671265 ~ 6.001286024128659e-11


Usher range:0.05207602514587067 ~ 1.7474385249020966e-07

# What happened after May?

In [1]:
import pandas as pd

In [8]:
dt_time=pd.read_csv('p_time_acc.csv',index_col=0)
rf_time=pd.read_csv('rf_time_acc.csv',index_col=0)
u_time=pd.read_csv('u_time_acc.csv',index_col=0)

In [15]:
dt_may=dt_time.loc[dt_time['earliest_date']>='2021-05-01'].rename(columns={'accuracy':'dt_accuracy'})
rf_may=rf_time.loc[rf_time['earliest_date']>='2021-05-01'].rename(columns={'accuracy':'rf_accuracy'})
u_may=u_time.loc[u_time['earliest_date']>='2021-05-01'].rename(columns={'accuracy':'u_accuracy'})
u_may

       lineage  u_accuracy earliest_date
83      AY.101       0.998    2021-05-01
85    AY.102.1       1.000    2021-07-08
86    AY.102.2       1.000    2021-07-12
88      AY.104       1.000    2021-07-05
89      AY.105       1.000    2021-05-12
...        ...         ...           ...
1526  P.1.10.2       1.000    2021-05-17
1527    P.1.11       1.000    2021-05-10
1529  P.1.12.1       1.000    2021-07-17
1543     P.1.8       1.000    2021-05-03
1573        XC       1.000    2021-08-12

[137 rows x 3 columns]

In [25]:
may1=pd.merge(dt_may,rf_may,on=['lineage','earliest_date'],how='outer')

may2=pd.merge(u_may,may1,on=['lineage','earliest_date'],how='outer')
may_sum=may2.drop(['lineage','earliest_date'], axis=1)
may_sum.to_csv('may_acc.csv')